#!/usr/bin/env python3
"""Generate combined data loss matrix across all image sizes"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import zipfile
import tempfile
from pathlib import Path
import argparse
import os
import re

def read_config_from_zip(zip_path):
    """Read configuration from simulation_logs.zip"""
    config = {}
    try:
        with zipfile.ZipFile(zip_path, 'r') as zipf:
            # Read sensor configuration - try multiple possible formats
            if 'configuration/sensor.dat' in zipf.namelist():
                with zipf.open('configuration/sensor.dat') as f:
                    content = f.read().decode().strip()
                    lines = content.split('\n')
                    
                    # Try the comma-separated format first
                    if len(lines) >= 2 and ',' in lines[1]:
                        # Format: bits-per-sense,pixel-count,pixel-size-m,focal-length-m,max-buffer-mb
                        data = lines[1].split(',')
                        if len(data) >= 5:
                            config['buffer_size_mb'] = float(data[4])
                        if len(data) >= 1:
                            # Calculate image size from bits-per-sense
                            bits_per_sense = int(data[0])
                            image_size_mb = bits_per_sense / (8 * 1024 * 1024)  # Convert bits to MB
                            config['image_size'] = image_size_mb
                    else:
                        # Try the space-separated format
                        for line in lines:
                            if line.startswith('sensor-image-size-MB'):
                                config['image_size'] = float(line.split()[-1])
                            elif line.startswith('max-buffer-mb'):
                                config['buffer_size_mb'] = float(line.split()[-1])
    except Exception as e:
        print(f"Warning: Could not read config from zip: {e}")
        config['image_size'] = 0.289  # Default fallback
        config['buffer_size_mb'] = 100000  # Default fallback
    
    return config

def calculate_loss_for_policy(policy_dir):
    """Calculate total data loss from buffer overflow logs (not estimates!)"""
    total_loss_mb = 0.0
    
    try:
        # Look for actual buffer overflow logs generated by the simulation
        overflow_files = [f for f in os.listdir(policy_dir) if f.startswith('meas-buffer-overflow-sat-') and f.endswith('.csv')]
        
        if not overflow_files:
            # No overflow files means no loss
            return 0.0
        
        for overflow_file in overflow_files:
            overflow_path = policy_dir / overflow_file
            if overflow_path.exists():
                try:
                    overflow_df = pd.read_csv(overflow_path)
                    if len(overflow_df) > 1 and len(overflow_df.columns) >= 2:
                        # Handle the potential empty third column
                        if len(overflow_df.columns) == 3:
                            overflow_df = overflow_df.iloc[:, :2]
                        
                        overflow_df.columns = ['timestamp', 'cumulative_loss_mb']
                        
                        # Get the final cumulative loss value for this satellite
                        cumulative_loss_values = pd.to_numeric(overflow_df['cumulative_loss_mb'], errors='coerce').dropna()
                        if len(cumulative_loss_values) > 0:
                            # Use the maximum cumulative loss (final value)
                            satellite_total_loss = cumulative_loss_values.max()
                            total_loss_mb += satellite_total_loss
                except Exception:
                    continue
    except Exception:
        pass
    
    return total_loss_mb

def calculate_loss_for_strategy(strategy_folder):
    """Calculate data loss from buffer overflow for all policies in a strategy"""
    policies = ["sticky", "roundrobin", "fifo", "random"]
    results = {}
    
    simulation_logs_zip = strategy_folder / "simulation_logs.zip"
    
    if not simulation_logs_zip.exists():
        print(f"   ❌ No simulation logs found")
        return {policy: (0, 0) for policy in policies}
    
    # Read configuration to get buffer size
    config = read_config_from_zip(simulation_logs_zip)
    buffer_size_mb = config.get('buffer_size_mb', 100000)
    
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        
        # Extract simulation logs
        with zipfile.ZipFile(simulation_logs_zip, 'r') as zipf:
            zipf.extractall(temp_path)
        
        for policy in policies:
            policy_dir = temp_path / policy
            
            if policy_dir.exists():
                # Calculate loss from buffer overflow logs
                total_loss_mb = calculate_loss_for_policy(policy_dir)
                
                # For display purposes, show both absolute MB and simple info
                results[policy] = (0, total_loss_mb)  # Percentage not meaningful for overflow
                
                if total_loss_mb > 0:
                    print(f"      🔸 {policy}: {total_loss_mb:.3f} MB lost from buffer overflow")
                else:
                    print(f"      🔸 {policy}: No buffer overflow (0.000 MB lost)")
            else:
                results[policy] = (0, 0)
                print(f"      ❌ {policy}: No data found")
    
    return results

def extract_image_size_from_folder(folder_name):
    """Extract image size from folder name like constellation_analysis_20251007_193320_28000_50"""
    # New format: constellation_analysis_YYYYMMDD_HHMMSS_IMAGESIZE_SATCOUNT
    # Extract the second-to-last number (image size), not the last (satellite count)
    match = re.search(r'_(\d+)_\d+$', folder_name)
    if match:
        size_str = match.group(1)
        # Convert to MB - add decimal point in appropriate position
        if len(size_str) == 5:  # 00028 -> 0.028, 28000 -> 28.000
            if size_str.startswith('000'):  # 00028 -> 0.028
                return float(size_str) / 1000
            else:  # 28000 -> 28.0
                return float(size_str) / 1000
        elif len(size_str) == 4:  # 0280 -> 0.280, 2800 -> 2.800
            return float(size_str) / 1000
        else:
            return float(size_str) / 1000
    return 0.289  # fallback

def extract_satellite_count_from_folder(folder_name):
    """Extract satellite count from folder name like constellation_analysis_20251007_193320_28000_50"""
    # New format: constellation_analysis_YYYYMMDD_HHMMSS_IMAGESIZE_SATCOUNT
    # Extract the last number (satellite count)
    match = re.search(r'_(\d+)$', folder_name)
    if match:
        return int(match.group(1))
    return None  # If no satellite count found, return None (old format)

def generate_combined_loss_matrix(base_folder, satellite_count=None):
    """Generate combined data loss matrix for specific satellite count (image size comparison only)"""
    
    base_path = Path(base_folder)
    
    constellation_info = f" ({satellite_count} satellites)" if satellite_count else ""
    print(f"=== Generating Combined Data Loss Matrix{constellation_info} ===")
    print(f"📁 Base folder: {base_folder}")
    
    # Find all analysis folders
    analysis_folders = [f for f in base_path.iterdir() 
                       if f.is_dir() and f.name.startswith('constellation_analysis_')]
    
    if not analysis_folders:
        print("❌ No analysis folders found!")
        return
    
    # Filter by satellite count if specified
    if satellite_count is not None:
        filtered_folders = []
        for folder in analysis_folders:
            folder_sat_count = extract_satellite_count_from_folder(folder.name)
            if folder_sat_count == satellite_count:
                filtered_folders.append(folder)
        
        if not filtered_folders:
            print(f"❌ No analysis folders found for {satellite_count} satellites")
            print(f"Available satellite counts:")
            sat_counts = set()
            for folder in analysis_folders:
                sat_count = extract_satellite_count_from_folder(folder.name)
                if sat_count is not None:
                    sat_counts.add(sat_count)
            for sc in sorted(sat_counts):
                print(f"  🛰️  {sc} satellites")
            return
        
        analysis_folders = filtered_folders
        print(f"🛰️  Filtering to {satellite_count} satellite constellation ({len(analysis_folders)} folders found)")
    
    # Sort folders and extract image sizes
    analysis_folders.sort()
    image_sizes = []
    for folder in analysis_folders:
        size = extract_image_size_from_folder(folder.name)
        image_sizes.append(size)
        print(f"  📁 {folder.name} → {size:.3f} MB")
    
    # Get buffer size from first folder's configuration
    buffer_size_mb = 100000  # Default
    if analysis_folders:
        first_folder = analysis_folders[0]
        strategies = [d for d in first_folder.iterdir() if d.is_dir()]
        if strategies:
            sim_logs = strategies[0] / "simulation_logs.zip"
            if sim_logs.exists():
                config = read_config_from_zip(sim_logs)
                buffer_size_mb = config.get('buffer_size_mb', 100000)
    
    print(f"\n📊 Buffer size: {buffer_size_mb:.0f} MB")
    
    strategies = ["close-spaced", "frame-spaced", "orbit-spaced", "close-orbit-spaced"]
    policies = ["sticky", "roundrobin", "fifo", "random"]
    
    # Create loss matrices: rows = policies × image_sizes, columns = strategies
    rows_per_policy = len(image_sizes)
    total_rows = len(policies) * rows_per_policy
    loss_matrix = np.zeros((total_rows, len(strategies)))  # Percentage values (not used)
    loss_mb_matrix = np.zeros((total_rows, len(strategies)))  # Absolute MB values
    
    # Process each image size
    for img_idx, (folder, image_size) in enumerate(zip(analysis_folders, image_sizes)):
        print(f"\n🔄 Processing image size {image_size:.3f} MB...")
        
        # Process each strategy
        for strategy_idx, strategy in enumerate(strategies):
            print(f"   📊 {strategy}:")
            strategy_folder = folder / strategy
            
            if strategy_folder.exists():
                loss_data = calculate_loss_for_strategy(strategy_folder)
                
                # Fill matrices for each policy
                for policy_idx, policy in enumerate(policies):
                    row_idx = policy_idx * rows_per_policy + img_idx
                    policy_data = loss_data.get(policy, (0, 0))
                    loss_percentage = policy_data[0] if isinstance(policy_data, tuple) else policy_data
                    loss_mb = policy_data[1] if isinstance(policy_data, tuple) else 0
                    
                    loss_matrix[row_idx, strategy_idx] = loss_percentage
                    loss_mb_matrix[row_idx, strategy_idx] = loss_mb
            else:
                print(f"      ❌ Strategy folder not found")
                # Fill with zeros for missing strategy
                for policy_idx, policy in enumerate(policies):
                    row_idx = policy_idx * rows_per_policy + img_idx
                    loss_matrix[row_idx, strategy_idx] = 0
                    loss_mb_matrix[row_idx, strategy_idx] = 0
    
    # Create visualization
    print(f"\n📈 Creating loss matrix visualization...")
    
    # Create figure
    fig, ax = plt.subplots(figsize=(16, 14))
    
    # Use Oranges colormap (higher loss = worse = darker orange)
    cmap = 'Oranges'
    better_text = "Lower Values = Better Performance (Less Data Loss)"
    
    # Create the heatmap using imshow
    im = ax.imshow(loss_mb_matrix, cmap=cmap, aspect='auto')
    
    # Set ticks and labels - strategies on X, policies with image sizes on Y
    strategy_labels = [s.replace('-', '-').title() for s in strategies]
    
    # Create Y-axis labels matching idle matrix format
    all_y_positions = []
    all_y_labels = []
    
    for policy_idx, policy in enumerate(policies):
        for img_idx, img_size in enumerate(image_sizes):
            row_idx = policy_idx * rows_per_policy + img_idx
            all_y_positions.append(row_idx)
            
            # Format size label to match idle matrix
            if img_size < 1:
                size_label = f".{int(img_size * 1000):03d}"  # .028, .289
            else:
                size_label = f"{img_size:.0f}"  # 3, 29
            
            # For the first row of each policy, show policy name to the left of image size
            if img_idx == 0:
                label = f"{policy.upper()}  {size_label}"  # Extra space for separation
            else:
                label = f"      {size_label}"  # Indent image sizes to align under policy
            
            all_y_labels.append(label)
    
    ax.set_xticks(np.arange(len(strategies)))
    ax.set_yticks(all_y_positions)
    ax.set_xticklabels(strategy_labels, fontsize=12, fontweight='bold')
    ax.set_yticklabels(all_y_labels, fontsize=10, fontweight='bold')
    
    # Add colorbar
    max_value = np.max(loss_mb_matrix)
    min_value = np.min(loss_mb_matrix)
    cbar = plt.colorbar(im, ax=ax, shrink=0.8)
    cbar.set_label('Data Loss (MB)', rotation=270, labelpad=20, fontsize=12, fontweight='bold')
    cbar.ax.tick_params(labelsize=10)
    
    # Add text annotations with values - show absolute MB from buffer overflow
    for policy_idx, policy in enumerate(policies):
        for img_idx, img_size in enumerate(image_sizes):
            row_idx = policy_idx * rows_per_policy + img_idx
            
            for strategy_idx, strategy in enumerate(strategies):
                loss_mb = loss_mb_matrix[row_idx, strategy_idx]
                
                # Format text showing MB lost from buffer overflow
                if loss_mb < 0.001:
                    value_text = f'0.000 MB\nNo Loss'
                else:
                    value_text = f'{loss_mb:.1f} MB\nOverflow'
                    
                text = ax.text(strategy_idx, row_idx, value_text, ha="center", va="center", 
                             color='black', fontweight='bold', fontsize=9)
    
    # Create comprehensive title
    constellation_title = f" ({satellite_count} Satellite Constellation)" if satellite_count else ""
    title = f'Data Loss Analysis{constellation_title}: All Image Sizes (Buffer: {buffer_size_mb:.0f} MB)\nEach cell shows 4 image sizes: {", ".join([f"{s:.3f}MB" for s in image_sizes])}\n{better_text}'
    
    # Titles and labels
    ax.set_title(title, fontsize=16, fontweight='bold', pad=25)
    ax.set_xlabel('Spacing Strategy', fontsize=14, fontweight='bold')
    ax.set_ylabel('Scheduling Policy (with Image Sizes)', fontsize=14, fontweight='bold')
    
    # Add horizontal grid lines to separate policies (every 4 rows)
    for policy_idx in range(1, len(policies)):
        ax.axhline(y=policy_idx * rows_per_policy - 0.5, color='black', linestyle='-', linewidth=3)
    
    # Add grid for better readability
    ax.set_xticks(np.arange(len(strategies)+1)-.5, minor=True)
    ax.set_yticks(np.arange(total_rows+1)-.5, minor=True)
    ax.grid(which="minor", color="gray", linestyle='-', linewidth=1)
    ax.tick_params(which="minor", size=0)
    
    # Rotate labels for better readability
    plt.xticks(rotation=45, ha='right')
    plt.yticks(rotation=0)
    
    plt.tight_layout()
    
    # Save the plot with satellite count in filename to constellation_analysis/loss_matrix/
    if satellite_count is not None:
        output_filename = f'combined_loss_matrix_{satellite_count}sats.png'
    else:
        output_filename = 'combined_loss_matrix.png'
    
    # Save to constellation_analysis/loss_matrix/ directory
    script_dir = Path(__file__).parent
    output_dir = script_dir / "constellation_analysis" / "loss_matrix"
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / output_filename
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    plt.close()
    print(f"\n✅ Combined loss matrix saved: {output_path}")
    
    # Print summary statistics
    print(f"\n📊 Loss Matrix Summary:")
    print(f"   🔹 Max loss: {max_value:.3f} MB")
    print(f"   🔹 Min loss: {min_value:.3f} MB")
    print(f"   🔹 Mean loss: {np.mean(loss_mb_matrix):.3f} MB")
    print(f"   🔹 Image sizes: {len(image_sizes)} ({', '.join([f'{s:.3f}MB' for s in image_sizes])})")
    print(f"   🔹 Strategies: {len(strategies)} ({', '.join(strategies)})")
    print(f"   🔹 Policies: {len(policies)} ({', '.join(policies)})")

def main():
    parser = argparse.ArgumentParser(description='Generate combined data loss matrix across image sizes for specific satellite count')
    parser.add_argument('base_folder', help='Base folder containing analysis results')
    parser.add_argument('--sats', type=int, help='Satellite count to filter by (e.g., 1, 50, 100, 200)')
    args = parser.parse_args()
    
    generate_combined_loss_matrix(args.base_folder, args.sats)

if __name__ == "__main__":
    main()